services:
  mongodb:
    image: mongo:7
    container_name: statistics-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: statistics_db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express:latest
    container_name: statistics-mongo-express
    restart: unless-stopped
    ports:
      - "8085:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: pass
    depends_on:
      - mongodb
